
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: *******
  password: *******
  port: 5432
  host: localhost



development:
  <<: *default
  database: react_movie_development

test:
  <<: *default
  database: react_movie_test
#     url: <%= ENV['DATABASE_URL'] %>
#
